---
title: "Day013"
output: rmarkdown::github_document
---

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
options(scipen = 999)
```

```{r message=FALSE}
library(plyr)
library(tidyverse)
```

Data loading
```{r}
app_train <- read.csv("data/application_train.csv")
app_test <- read.csv("data/application_train.csv")
```

Label encoding
```{r}
feature.names <- colnames(app_train)
count <- 0

# Iterate through the columns
for (f in feature.names) {
    if (class(app_train[[f]]) == 'factor') {
        if (nlevels(app_train[[f]]) <= 2) {
        levels <- list(app_train[[f]], app_test[[f]]) %>% unlist() %>% levels()
        app_train[[f]] <- mapvalues(app_train[[f]], from=levels, to=c(1,2)) %>% as.integer()
        app_test[[f]] <- mapvalues(app_test[[f]], from=levels, to=c(1,2)) %>% as.integer()
        count <- count + 1
        }
    }
}

print(paste(count,"labels were label encoded."))
```

```{r}
# Create an anomalous flag column
app_train$DAYS_EMPLOYED_ANOM <- app_train$DAYS_EMPLOYED == 365243
app_train$DAYS_EMPLOYED[which(app_train$DAYS_EMPLOYED == 365243)] <- NA

# also apply to testing dataset
app_test$DAYS_EMPLOYED_ANOM <- app_test$DAYS_EMPLOYED == 365243
app_test$DAYS_EMPLOYED[which(app_test$DAYS_EMPLOYED == 365243)] <- NA

# absolute the value of DAYS_BIRTH
app_train$DAYS_BIRTH <- abs(app_train$DAYS_BIRTH)
app_test$DAYS_BIRTH <- abs(app_test$DAYS_BIRTH)

# absolute the value of DAYS_EMPLOYED
app_train$DAYS_EMPLOYED <- abs(app_train$DAYS_EMPLOYED)
app_test$DAYS_EMPLOYED <- abs(app_test$DAYS_EMPLOYED)
```


##離散化DAYS_EMPLOYED

等寬劃分
```{r}
days_employed <- app_train$DAYS_EMPLOYED[!is.na(app_train$DAYS_EMPLOYED)]

breaks <- seq(min(days_employed), max(days_employed), length.out = 11)
EQUAL_WIDTH = cut(days_employed, breaks = breaks)
table(EQUAL_WIDTH)
```

等頻劃分
```{r}
breaks <- quantile(days_employed, probs = 0:10/10)
breaks
EQUAL_FREQUENCY = cut(days_employed, breaks = breaks, include.lowest=TRUE)
table(EQUAL_FREQUENCY)
```


```{r}
DAYS_EMPLOYED <- data.frame(DAYS_EMPLOYED = days_employed,
                            EQUAL_WIDTH = EQUAL_WIDTH,
                            EQUAL_FREQUENCY = EQUAL_FREQUENCY)
head(DAYS_EMPLOYED)
```
```{r}
ggplot(DAYS_EMPLOYED, aes(x = EQUAL_WIDTH, fill = EQUAL_WIDTH)) +
  geom_histogram(stat = "count") +
  theme(axis.text.x = element_text(angle = 75, hjust = 1)) +
  ggtitle("Histogram of DAYS_EMPLOYED (Equal Width)")
```
```{r}
ggplot(DAYS_EMPLOYED, aes(x = EQUAL_FREQUENCY, fill = EQUAL_FREQUENCY)) +
  geom_histogram(stat = "count") +
  theme(axis.text.x = element_text(angle = 75, hjust = 1)) +
  ggtitle("Histogram of DAYS_EMPLOYED (Equal Frequency)")
```




