---
title: "Day021"
output: rmarkdown::github_document
---

## HW (Kaggle)鐵達尼生存預測精簡版  
https://www.kaggle.com/c/titanic  


```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
```
Packages loading
```{r message=FALSE}
library(purrr)
library(plyr)
library(tidyverse)
library(caret)
library(ROCR)
```

Data loading  
```{r}
df_train <- read.csv("data/titanic_train.csv")
df_test <- read.csv("data/titanic_test.csv")
sapply(list(df_train=df_train, df_test=df_test), dim) %>% 'rownames<-'(c('nrow','ncol')) 
```

Setting training and testing data  
```{r}
train_y <- df_train$Survived
ids <- df_test$PassengerId
df_train <- df_train %>% select(-c("Survived","PassengerId"))
df_test <- df_test %>% select(-"PassengerId")
df <- rbind(df_train, df_test)
head(df)
```

秀出資料欄位的類型與數量
```{r}
table(sapply(df, class))
```
確定只有 integer, numeric, factor 三種類型後, 分別將欄位名稱存於三個 vector 中
```{r}
feature_type <- sapply(df, class)
int_var <- feature_type[which(feature_type == "integer")] %>% as.data.frame %>% rownames
num_var <- feature_type[which(feature_type == "numeric")] %>% as.data.frame %>% rownames
fac_var <- feature_type[which(feature_type == "factor")] %>% as.data.frame %>% rownames
list(integer_feature = int_var,
     numeric_feature = num_var,
     factor_feature = fac_var)
```

削減文字型欄位, 只剩數值型欄位
```{r}
df <- df %>% select(-fac_var)
train_num <- length(train_y)
head(df)
```
##作業1
試著在鐵達尼的票價 (Fare) 欄位中使用對數去偏 (log1p) , 結果是否更好?
```{r}
# 做線性迴歸, 觀察分數
df_m1 <- df %>% replace(., is.na(.), -1) # 缺失值補-1
train_x <- df_m1[1:train_num,] 
normal <- preProcess(train_x, method = "range", rangeBounds = c(0,1)) # 最小最大化
train_normal <- predict(normal, train_x)
train <- train_normal %>% mutate(Survived = train_y)
control <- trainControl(method="cv", number=5) # 交叉驗證, folds=5
fit <- train(Survived~., data=train, method="lm", metric="Rsquared", trControl=control)
# display results
print(fit)
```

Density histogram of Fare
```{r}
ggplot(train, aes(x = Fare)) +
    geom_histogram(aes(y = ..density..), alpha = .7, linetype = "blank") +
    geom_density(alpha = .3) +
    ggtitle(paste0("Density histogram of Fare"," (Rsquared = ",round(fit$results["Rsquared"],3),")"))
```
```{r}
# 做線性迴歸, 觀察分數
df_m1 <- df %>% replace(., is.na(.), -1) # 缺失值補-1
train_x_fixed <- df_m1[1:train_num,] %>% mutate(log_Fare = log1p(train_x$Fare)) %>% select(-"Fare")
fixed_normal <- preProcess(train_x_fixed, method = "range", rangeBounds = c(0,1)) # 最小最大化
train_fixed_normal <- predict(fixed_normal, train_x_fixed)
train_fixed <- train_fixed_normal %>% mutate(Survived = train_y)
control <- trainControl(method="cv", number=5) # 交叉驗證, folds=5
fix_fit <- train(Survived~., data=train_fixed, method="lm", metric="Rsquared", trControl=control)
# display results
print(fix_fit)
```
Density histogram of log1p(Fare)  
```{r}
ggplot(train_fixed, aes(x = log_Fare)) +
    geom_histogram(aes(y = ..density..), alpha = .7, linetype = "blank") +
    geom_density(alpha = .3) +
    ggtitle(paste0("Density histogram of Fare"," (Rsquared = ",round(fix_fit$results["Rsquared"],3),")"))
```
  
##作業2
最後的 boxcox 區塊直接執行會造成錯誤, 起因為輸入值有負值, 請問如何修正後可以使用 boxcox? (Hint : 試圖修正資料)
```{r}
# 做線性迴歸, 觀察分數
train_x <- df[1:train_num,]
train_x$Fare <- train_x$Fare + 1 # Note that BoxCox is applied to positive values
myBoxCoxTrans <- BoxCoxTrans(train_x$Fare)
myBoxCoxTrans
train_x$Fare <- predict(myBoxCoxTrans, train_x$Fare)

ggplot(train_x, aes(x = Fare)) +
    geom_histogram(aes(y = ..density..), alpha = .7, linetype = "blank") +
    geom_density(alpha = .3) +
    ggtitle(paste0('Density histogram of BoxCox Fare'," (lambda = ", round(myBoxCoxTrans$lambda,3), ")"))
```
```{r}
train_x_m1 <- train_x %>% replace(., is.na(.), -1) # 缺失值補-1
normal <- preProcess(train_x_m1, method = "range", rangeBounds = c(0,1)) # 最小最大化
train_normal <- predict(normal, train_x_m1)
train <- train_normal %>% mutate(Survived = train_y)
control <- trainControl(method="cv", number=5) # 交叉驗證, folds=5
fit <- train(Survived~., data=train, method="lm", metric="Rsquared", trControl=control)
# display results
print(fit)
```

