---
title: "Day018"
output: rmarkdown::github_document
---

## HW (Kaggle)鐵達尼生存預測精簡版  
https://www.kaggle.com/c/titanic  


```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
```
Packages loading
```{r message=FALSE}
library(purrr)
library(plyr)
library(tidyverse)
library(caret)
```

Data loading  
```{r}
df_train <- read.csv("data/titanic_train.csv")
df_test <- read.csv("data/titanic_test.csv")
dim(df_train)
```

Setting training and testing data  
```{r}
train_y <- df_train$Survived
ids <- df_test$PassengerId
df_train <- df_train %>% select(-c("Survived","PassengerId"))
df_test <- df_test %>% select(-"PassengerId")
df <- rbind(df_train, df_test)
head(df)
```
秀出資料欄位的類型與數量
```{r}
table(sapply(df, class))
```
確定只有 integer, numeric, factor 三種類型後, 分別將欄位名稱存於三個 vector 中
```{r}
feature_type <- sapply(df, class)
int_var <- feature_type[which(feature_type == "integer")] %>% as.data.frame %>% rownames
num_var <- feature_type[which(feature_type == "numeric")] %>% as.data.frame %>% rownames
fac_var <- feature_type[which(feature_type == "factor")] %>% as.data.frame %>% rownames
list(integer_feature = int_var,
     numeric_feature = num_var,
     factor_feature = fac_var)
```
###作業1  

試著執行作業程式，觀察三種類型 (int / float / object) 的欄位分別進行( 平均 mean / 最大值 Max / 相異值 nunique )
中的九次操作會有那些問題? 並試著解釋那些發生Error的程式區塊的原因?
```{r}
list(Mean = df[int_var] %>% sapply(mean, na.rm = TRUE),
     Max = df[int_var] %>% sapply(max, na.rm = TRUE),
     Unique = df[int_var] %>% sapply(unique))
```
```{r}
list(Mean = df[num_var] %>% sapply(mean, na.rm = TRUE),
     Max = df[num_var] %>% sapply(max, na.rm = TRUE),
     Unique = df[num_var] %>% sapply(unique))
```
```{r eval = FALSE}
list(Mean = df[fac_var] %>% sapply(mean, na.rm = TRUE),
     Max = df[fac_var] %>% sapply(max, na.rm = TRUE),
     Unique = df[fac_var] %>% sapply(unique))
```
###作業2
  
思考一下，試著舉出今天五種類型以外的一種或多種資料類型，你舉出的新類型是否可以歸在三大類中的某些大類?
所以三大類特徵中，哪一大類處理起來應該最複雜?  




