---
title: "Day004"
output: rmarkdown::github_document
---
```{r message=FALSE}
library(magrittr)
library(tidyverse)
library(caret)
```


##Label Encoding
把每個類別 mapping 到某個整數，不會增加新欄位

```{r eval=FALSE}
# encoding all character features into ids with sort by name
count <- 0
for (f in feature.names) {
    if (class(train[[f]]) == 'factor') {
        levels <- sort(unique(c(train[[f]], test[[f]])))
        train[[f]] <- as.integer(factor(train[[f]], levels = levels))
        test[[f]] <- as.integer(factor(test[[f]], levels = levels))
        count <- count + 1
    }
}

print(paste(count,"labels were label encoded."))
```


Label encoding 的表示方式會讓同一個欄位底下的類別之間有大小關係 (0<1<2<...)，所以在這裡我們只對有類別數量小於等於 2 的類別型欄位示範使用 Label encoding，但不表示這樣處理是最好的，一切取決於欄位本身的意義適合哪一種表示方法
```{r eval=FALSE}
count <- 0
for (f in feature.names) {
    if (nlevels(train[[f]]) = 1) {
        levels <- sort(unique(c(train[[f]], test[[f]])))
        train[[f]] <- as.integer(factor(train[[f]], levels = levels))
        test[[f]] <- as.integer(factor(test[[f]], levels = levels))
        count <- count + 1
    }
}

print(paste(count,"labels were label encoded."))
```


##One Hot Encoding
```{r eval=FALSE}
library(caret)
dmy <- dummyVars(" ~ .", data = data)
dummy_df <- data.frame(predict(dmy, newdata = data))
```

##HW
檢視資料中各個欄位類型的數量
```{r}
app_train <- read.csv("data/application_train.csv")
sapply(app_train,class) %>% as.factor() %>% summary()
```

檢視資料中類別型欄位各自類別的數量 
```{r}
n_level <- sapply(app_train,nlevels) 
n_level[n_level>0]
```


```{r}
sub_train <- app_train$WEEKDAY_APPR_PROCESS_START %>% as.data.frame()

dmy <- dummyVars(" ~ .", data = sub_train)
df <- data.frame(predict(dmy, newdata = sub_train))
df %>% set_colnames(sort(unique(sub_train[,1]))) %>% head()
```



