---
title: "Day024"
output: rmarkdown::github_document
---
  
## HW (Kaggle)鐵達尼生存預測精簡版  
https://www.kaggle.com/c/titanic  


```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
```
Packages loading
```{r message=FALSE}
library(purrr)
library(magrittr)
library(plyr)
library(tidyverse)
library(caret)
library(hash)
library(pROC)
```

Data loading  
```{r}
df_train <- read.csv("data/titanic_train.csv")
df_test <- read.csv("data/titanic_test.csv")
sapply(list(df_train=df_train, df_test=df_test), dim) %>% 'rownames<-'(c('nrow','ncol')) 
```

Setting training and testing data  
```{r}
train_y <- df_train$Survived
ids <- df_test$PassengerId
df_train <- df_train %>% select(-c("Survived","PassengerId"))
df_test <- df_test %>% select(-"PassengerId")
df <- rbind(df_train, df_test)
```

```{r}
nlevels(df$Cabin)
```


秀出資料欄位的類型與數量
```{r}
table(sapply(df, class))
```
確定只有 integer, numeric, factor 三種類型後, 分別將欄位名稱存於三個 vector 中
```{r}
feature_type <- sapply(df, class)
int_var <- feature_type[which(feature_type == "integer")] %>% as.data.frame %>% rownames
num_var <- feature_type[which(feature_type == "numeric")] %>% as.data.frame %>% rownames
fac_var <- feature_type[which(feature_type == "factor")] %>% as.data.frame %>% rownames
list(integer_feature = int_var,
     numeric_feature = num_var,
     factor_feature = fac_var)
```

只留文字型欄位
```{r}
df <- df %>% select(fac_var)
train_num <- length(train_y)

# Fill empty entry with None
feature.names <- colnames(df)
for (f in feature.names) {
  df[[f]] <- mapvalues(df[[f]], from="", to="None")
}
```
   
標籤編碼
```{r}
feature.names <- colnames(df)
count <- 0

df_le <- df
# Iterate through the columns
for (f in feature.names) {
  levels <- df[[f]] %>% unlist() %>% levels()
  df_le[[f]] <- mapvalues(df[[f]], from=levels, to=seq_along(levels)) %>% as.integer()
  count <- count + 1
}
```
  
對照組 : 標籤編碼 + 邏輯斯迴歸   
```{r}
train_le <- df_le[1:train_num,] %>% mutate(Survived = as.factor(train_y))
levels(train_le$Survived) <- make.names(levels(factor(train_le$Survived)))
control <- trainControl(method="cv", number=5, classProbs=TRUE, summaryFunction=twoClassSummary)
fit_le <- train(Survived~., data=train_le, method="glm", metric="ROC", trControl=control)
# display results
print(fit_le)
```
```{r}
glm.probs <- predict(fit_le, data = train_le$Survived, type = "prob")
glm.ROC <- roc(response = train_le$Survived,
               predictor = glm.probs$X1,
               levels = levels(train_le$Survived))
plot(glm.ROC, type="S", col="red"); text(x=0, y=.25, labels=paste("AUC =", round(glm.ROC$auc, 4)))
```
  
加上 'Cabin' 欄位的計數編碼
```{r}
df_count <- df %>% 
  group_by(Cabin) %>% 
  count() %>% 
  set_colnames(c("Cabin","Cabin_Count")) %>%
  right_join(df) %>%
  ungroup

df_count %>% head
```   
   
'Cabin'計數編碼 + 邏輯斯迴歸
```{r}
# 對df_count做標籤編碼
feature.names <- colnames(df)
count <- 0

df_count_le <- df_count
# Iterate through the columns
for (f in feature.names) {
  levels <- df[[f]] %>% unlist() %>% levels()
  df_count_le[[f]] <- mapvalues(df[[f]], from=levels, to=seq_along(levels)) %>% as.integer()
  count <- count + 1
}
df_count_le %>% head
```
```{r}
train_count_le <- df_count_le[1:train_num,] %>% mutate(Survived = as.factor(train_y))
levels(train_count_le$Survived) <- make.names(levels(factor(train_count_le$Survived)))
control <- trainControl(method="cv", number=5, classProbs=TRUE, summaryFunction=twoClassSummary)
fit_count_le <- train(Survived~., data=train_count_le, method="glm", metric="ROC", trControl=control)
# display results
print(fit_count_le)
```
```{r}
glm.probs <- predict(fit_count_le, data = train_count_le$Survived, type = "prob")
glm.ROC <- roc(response = train_count_le$Survived,
               predictor = glm.probs$X1,
               levels = levels(train_count_le$Survived))
plot(glm.ROC, type="S", col="red"); text(x=0, y=.25, labels=paste("AUC =", round(glm.ROC$auc, 4)))
```
   
'Cabin'特徵雜湊 + 邏輯斯迴歸
```{r}
h <- hash(df$Cabin, seq_along(df$Cabin))
Cabin_hashed <- values(h) %>% 
  as.table %>% 
  as.data.frame %>%
  set_colnames(c("Cabin", "Cabin_Hash"))
Cabin_hashed[["Cabin_Hash"]] <- Cabin_hashed$Cabin_Hash %% 10 # mod 
Cabin_hashed %>% head
```
```{r}
df_hashed <- df %>%
  left_join(Cabin_hashed)
df_hashed %>% head
```
```{r}
# 對df_hashed做標籤編碼
feature.names <- colnames(df)
count <- 0

df_hashed_le <- df_hashed
# Iterate through the columns
for (f in feature.names) {
  levels <- df[[f]] %>% unlist() %>% levels()
  df_hashed_le[[f]] <- mapvalues(df[[f]], from=levels, to=seq_along(levels)) %>% as.integer()
  count <- count + 1
}
df_hashed_le %>% head
```
```{r}
train_hashed_le <- df_hashed_le[1:train_num,] %>% mutate(Survived = as.factor(train_y))
levels(train_hashed_le$Survived) <- make.names(levels(factor(train_hashed_le$Survived)))
control <- trainControl(method="cv", number=5, classProbs=TRUE, summaryFunction=twoClassSummary)
fit_hashed_le <- train(Survived~., data=train_hashed_le, method="glm", metric="ROC", trControl=control)
# display results
print(fit_hashed_le)
```
```{r}
glm.probs <- predict(fit_hashed_le, data = train_hashed_le$Survived, type = "prob")
glm.ROC <- roc(response = train_hashed_le$Survived,
               predictor = glm.probs$X1,
               levels = levels(train_hashed_le$Survived))
plot(glm.ROC, type="S", col="red"); text(x=0, y=.25, labels=paste("AUC =", round(glm.ROC$auc, 4)))
```
  
'Cabin'計數編碼 + 'Cabin'特徵雜湊 + 邏輯斯迴歸
```{r}
df_count_hashed <- df_count %>%
  left_join(Cabin_hashed)
df_count_hashed %>% head
```
```{r}
# 對df_count_hashed做標籤編碼
feature.names <- colnames(df)
count <- 0

df_count_hashed_le <- df_count_hashed
# Iterate through the columns
for (f in feature.names) {
  levels <- df[[f]] %>% unlist() %>% levels()
  df_count_hashed_le[[f]] <- mapvalues(df[[f]], from=levels, to=seq_along(levels)) %>% as.integer()
  count <- count + 1
}
df_count_hashed_le %>% head
```
```{r}
train_count_hashed_le <- df_count_hashed_le[1:train_num,] %>% mutate(Survived = as.factor(train_y))
levels(train_count_hashed_le$Survived) <- make.names(levels(factor(train_count_hashed_le$Survived)))
control <- trainControl(method="cv", number=5, classProbs=TRUE, summaryFunction=twoClassSummary)
fit_count_hashed_le <- train(Survived~., data=train_count_hashed_le, method="glm", metric="ROC", trControl=control)
# display results
print(fit_count_hashed_le)
```
```{r}
glm.probs <- predict(fit_count_hashed_le, data = train_hashed_le$Survived, type = "prob")
glm.ROC <- roc(response = train_count_hashed_le$Survived,
               predictor = glm.probs$X1,
               levels = levels(train_count_hashed_le$Survived))
plot(glm.ROC, type="S", col="red"); text(x=0, y=.25, labels=paste("AUC =", round(glm.ROC$auc, 4)))
```
