---
title: "Day008"
output: rmarkdown::github_document
---

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
```

```{r message=FALSE}
library(magrittr)
library(tidyverse)
library(gridExtra)
```

##1. 請將 app_train 中的 CNT_CHILDREN 依照下列規則分為四組，並將其結果在原本的 dataframe 命名為 CNT_CHILDREN_GROUP
```{r}
app_train <- read.csv("data/application_train.csv")
```

```{r}
breaks <- c(-Inf,0,2,5,Inf)
app_train <- mutate(app_train, CNT_CHILDREN_GROUP = cut(CNT_CHILDREN, breaks = breaks))
```
  
##2. 請根據 CNT_CHILDREN_GROUP 以及 TARGET，列出各組的平均 AMT_INCOME_TOTAL，並繪製 boxplot
```{r}
app_train %>% 
  group_by(CNT_CHILDREN_GROUP) %>%
  summarise(mean(AMT_INCOME_TOTAL))
```
```{r fig.align = "center"}
p1 <- ggplot(data = app_train) +
  geom_boxplot(aes(x=CNT_CHILDREN_GROUP, y=AMT_INCOME_TOTAL)) 

p2 <- ggplot(data = app_train) +
  geom_boxplot(aes(x=CNT_CHILDREN_GROUP, y=log(AMT_INCOME_TOTAL)))

grid.arrange(p1,p2,ncol=2)
```
```{r}
app_train %>% 
  group_by(TARGET) %>%
  summarise(mean(AMT_INCOME_TOTAL))
```
```{r fig.align = "center"}
app_train$TARGET <- as.factor(app_train$TARGET)

p3 <- ggplot(data = app_train) +
  geom_boxplot(aes(x=TARGET, y=AMT_INCOME_TOTAL)) 

p4 <- ggplot(data = app_train) +
  geom_boxplot(aes(x=TARGET, y=log(AMT_INCOME_TOTAL)))

grid.arrange(p3,p4,ncol=2)
```
  
##3. 請根據 CNT_CHILDREN_GROUP 以及 TARGET，對 AMT_INCOME_TOTAL 計算 Z 轉換 後的分數
```{r}
app_train %>% 
  group_by(CNT_CHILDREN_GROUP) %>%
  mutate(GROUP_MEAN = mean(AMT_INCOME_TOTAL),
         GROUP_SD = sd(AMT_INCOME_TOTAL)) %>%
  mutate(Z_TRANSFORM = (AMT_INCOME_TOTAL - GROUP_MEAN) / GROUP_SD) %>%
  select(CNT_CHILDREN_GROUP ,AMT_INCOME_TOTAL, GROUP_MEAN, GROUP_SD, Z_TRANSFORM) %>%
  head()
```
```{r}
app_train %>% 
  group_by(TARGET) %>%
  mutate(GROUP_MEAN = mean(AMT_INCOME_TOTAL),
         GROUP_SD = sd(AMT_INCOME_TOTAL)) %>%
  mutate(Z_TRANSFORM = (AMT_INCOME_TOTAL - GROUP_MEAN) / GROUP_SD) %>%
  select(TARGET, AMT_INCOME_TOTAL, GROUP_MEAN, GROUP_SD, Z_TRANSFORM) %>%
  head()
```











