---
title: "Day036"
output: rmarkdown::github_document
---

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
Sys.setlocale(category = "LC_ALL", locale = "UTF-8")
```

```{r message=FALSE}
library(tidyverse)
library(caret)
```
  
## 回歸問題
常見的評估指標有  
-MAE  
-MSE  
-R-square  

```{r}
e <- rnorm(1000, mean=0, sd=1)
X <- rnorm(1000, mean=5)
y <- 1 + X*2 + e 
fit <- lm(y~X)
evaluation <- list(MAE <- MAE(fit$fitted.values, y),
                   MSE <- mean(fit$residuals^2),
                   R.squared <- summary(fit)$r.squared) 
names(evaluation) <- c('MAE', 'MSE', 'R.squared')
evaluation
```
  
## 分類問題
常見的評估指標有  
-AUC  
-F1-Score (Precision, Recall)  


\[F_{\beta}=\frac{(1+\beta^2)(precision*recall)}{(\beta^2*precision+recall)}\]
試著寫出 F2-Score 的計算函數  
```{r}
y_pred <- sample(c(0,1), 100, replace=TRUE) %>% as.factor
y_true <- sample(c(0,1), 100, replace=TRUE) %>% as.factor
```


```{r}
f2_score <- function(y_pred, p_true, beta) {
  precision <- precision(data=y_pred, reference=y_true)
  recall <- recall(data=y_pred, reference=y_true)
  return(((1+beta^2)*(precision*recall))/(beta^2*precision+recall))
}

f2_score(y_pred, p_true, 2)
```
Caret::F_meas()  
```{r}
F_meas(data=y_pred, reference=y_true, beta=2)
```

